"use client";

import React from "react";
import Head from "next/head";
import { useState } from "react";
import output from "../declensions/output";
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";
import RootLayout from "./layout";
import { Button } from "@/components/ui/button";

const initialState = {
  verb: "",
  presentDeclension: null,
  present: false,
  imperfect: false,
  future: false,
  aorist: false,
  perfect: false,
  pluperfect: false,
  active: false,
  middle: false,
  passive: false,
  indicative: false,
  subjunctive: false,
  optative: false,
  imperative: false,
  tense: false,
  voice: false,
  mood: false,
  error: false,
};

export default function Home() {
  const [presentDeclension, setPresentDeclension] =
    useState<React.ReactElement | null>(null);

  const [data, setData] = useState<{
    [k: string]: boolean | string | React.ReactElement | null;
  }>(initialState);

  function handleChange(
    fieldName: string,
    fieldValue: boolean | string | React.ReactElement | null
  ) {
    setData((prev) => ({
      ...prev,
      [fieldName]: fieldValue,
    }));
  }

  const isTenseSelected = () => {
    setData((prev) => ({
      ...prev,
      tense: false,
    }));
    if (
      data.present ||
      data.imperfect ||
      data.aorist ||
      data.future ||
      data.perfect ||
      data.pluperfect === true
    ) {
      setData((prev) => ({
        ...prev,
        tense: true,
      }));
    }
  };

  console.log("Tense", data.tense);

  const isVoiceSelected = () => {
    setData((prev) => ({
      ...prev,
      voice: false,
    }));
    if (data.active || data.middle || data.passive === true) {
      setData((prev) => ({
        ...prev,
        voice: true,
      }));
    }
  };

  const isMoodSelected = () => {
    setData((prev) => ({
      ...prev,
      mood: false,
    }));
    if (
      data.indicative ||
      data.subjunctive ||
      data.optative ||
      data.imperative === true
    ) {
      setData((prev) => ({
        ...prev,
        mood: true,
      }));
    }
  };

  const submitForm = (e: any) => {
    e.preventDefault();
    // if (!tense && !voice && !mood) return;
    isTenseSelected(), isVoiceSelected(), isMoodSelected();

    if (data.tense === false || data.mood === false || data.voice === false) {
      console.log("There is a problem");
      return;
    } else {
      setPresentDeclension(
        output({
          verb: data.verb as string,
          active: data.active as boolean,
          middle: data.middle as boolean,
          passive: data.passive as boolean,
          indicative: data.indicative as boolean,
          subjunctive: data.indicative as boolean,
          optative: data.indicative as boolean,
          imperative: data.indicative as boolean,
          present: data.indicative as boolean,
          imperfect: data.indicative as boolean,
          future: data.indicative as boolean,
          aorist: data.indicative as boolean,
        })
      );
    }
  };

  console.log("error", data.error);
  console.log("declension", presentDeclension);

  return (
    <RootLayout>
      <div>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className="flex flex-col items-center justify-center p-12">
          <div className="w-5/6">
            <h1 className="text-6xl text-center pb-3">Smart Verb Declenator</h1>
            <div className="flex justify-center items-center">
              <input
                className="mt-2 mb-2 pl-2 pr-2 border-2 border-white rounded-sm focus:border-b-blue-300"
                required
                id="verb"
                type="text"
                onChange={(e: any) => handleChange("verb", e.target.value)}
                value={data.verb as string}
              />
            </div>
            <div className="flex flex-col justify-center items-center">
              <Accordion type="multiple" className="w-96">
                <AccordionItem className="flex flex-col" value="item-1">
                  <AccordionTrigger>Choose Tense</AccordionTrigger>
                  <AccordionContent>
                    <div>
                      <input
                        required
                        id="present"
                        type="checkbox"
                        name="declension"
                        checked={data.present as boolean}
                        onClick={() => handleChange("present", !data.present)}
                      />
                      <label htmlFor="present">Present</label>
                    </div>
                    <div>
                      <input
                        required
                        id="imperfect"
                        type="checkbox"
                        name="declension"
                        checked={data.imperfect as boolean}
                        onClick={() =>
                          handleChange("imperfect", !data.imperfect)
                        }
                      />
                      <label htmlFor="imperfect">Imperfect</label>
                    </div>
                    <div>
                      <input
                        required
                        id="future"
                        type="checkbox"
                        name="declension"
                        checked={data.future as boolean}
                        onClick={() => handleChange("future", !data.future)}
                      />
                      <label htmlFor="future">Future</label>
                    </div>
                    <div>
                      <input
                        required
                        id="aorist"
                        type="checkbox"
                        name="declension"
                        checked={data.aorist as boolean}
                        onClick={() => handleChange("aorist", !data.aorist)}
                      />
                      <label htmlFor="Aorist">Aorist</label>
                    </div>
                    <div>
                      <input
                        required
                        id="perfect"
                        type="checkbox"
                        name="declension"
                        checked={data.perfect as boolean}
                        onClick={() => handleChange("perfect", !data.perfect)}
                      />
                      <label htmlFor="perfect">Perfect</label>
                    </div>
                    <div>
                      <input
                        required
                        id="pluperfect"
                        type="checkbox"
                        name="declension"
                        checked={data.pluperfect as boolean}
                        onClick={() =>
                          handleChange("pluperfect", !data.pluperfect)
                        }
                      />
                      <label htmlFor="pluperfect">Pluperfect</label>
                    </div>
                    {data.error && !data.tense && (
                      <div>Please check at least one tense</div>
                    )}
                  </AccordionContent>
                </AccordionItem>
                <AccordionItem className="flex flex-col" value="item-2">
                  <AccordionTrigger>
                    <h3>Voice</h3>
                  </AccordionTrigger>
                  <AccordionContent>
                    <div>
                      <input
                        required
                        id="active"
                        type="checkbox"
                        name="declension"
                        checked={data.active as boolean}
                        onClick={() => handleChange("active", !data.active)}
                      />
                      <label htmlFor="active">Active</label>
                    </div>
                    <div>
                      <input
                        required
                        id="middle"
                        type="checkbox"
                        name="declension"
                        checked={data.middle as boolean}
                        onClick={() => handleChange("middle", !data.middle)}
                      />
                      <label htmlFor="middle">Middle</label>
                    </div>
                    <div>
                      <input
                        required
                        id="passive"
                        type="checkbox"
                        name="declension"
                        checked={data.passive as boolean}
                        onClick={() => handleChange("passive", !data.passive)}
                      />
                      <label htmlFor="middle">Passive</label>
                    </div>
                    {data.error && !data.voice && (
                      <div>Please check at least one tense</div>
                    )}
                  </AccordionContent>
                </AccordionItem>
                <AccordionItem value="item-3" className="flex flex-col">
                  <AccordionTrigger>
                    <h3>Mood</h3>
                  </AccordionTrigger>
                  <AccordionContent>
                    <div>
                      <input
                        required
                        id="indicative"
                        type="checkbox"
                        name="declension"
                        checked={data.indicative as boolean}
                        onClick={() =>
                          handleChange("indicative", !data.indicative)
                        }
                      />
                      <label htmlFor="indicative">Indicative</label>
                    </div>
                    <div>
                      <input
                        required
                        id="subjunctive"
                        type="checkbox"
                        name="declension"
                        checked={data.subjunctive as boolean}
                        onClick={() =>
                          handleChange("subjunctive", !data.subjunctive)
                        }
                      />
                      <label htmlFor="subjunctive">Subjunctive</label>
                    </div>
                    <div>
                      <input
                        required
                        id="optative"
                        type="checkbox"
                        name="declension"
                        checked={data.optative as boolean}
                        onClick={() => handleChange("optative", !data.optative)}
                      />
                      <label htmlFor="optative">Optative</label>
                    </div>
                    <div>
                      <input
                        required
                        id="imperative"
                        type="checkbox"
                        name="declension"
                        checked={data.imperative as boolean}
                        onClick={() =>
                          handleChange("imperative", !data.imperative)
                        }
                      />
                      <label htmlFor="optative">Imperative</label>
                    </div>
                    {data.error && !data.mood && (
                      <div>Please check at least one tense</div>
                    )}
                  </AccordionContent>
                </AccordionItem>
              </Accordion>
            </div>
            <div className="flex flex-col justify-center items-center">
              <Button variant={"outline"} id="verb" onClick={submitForm}>
                Submit
              </Button>
            </div>
            <div>
              {data.tense &&
              data.voice &&
              data.mood &&
              (data.verb as string).length
                ? presentDeclension
                : null}
            </div>
            <div>
              {data.error ? <div>Please check your options</div> : null}
            </div>
          </div>
        </main>
      </div>
    </RootLayout>
  );
}
